meta:
  engine: 4.1.0 # Min Ergogen version for KiCad 8 footprints
  version: 0.1
  author: "SimplyYat"
units:
  # Key Size Variables (cx and cy are choc sizes, replace with u for mx)
  kx: cx
  ky: cy
  # Switch size variables
  sx: 14
  sy: 14
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Half values
  halfX: (px / 2)
  halfY: (py / 2)
  # Double half values
  dHalfX: (dpx / 2)
  dHalfY: (dpy / 2)
  # Defaults to M2 Screw Inserts
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      anchor:
        rotate: 5
        # Fix placement on KiCAD sheet.
        shift: [100, -100]
      columns:
        pinky:
          rows.r5.skip: true
          key.column_net: P031
          key.mirror.column_net: P006
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 12
          rows.r5.skip: true
          key.column_net: P029
          key.mirror.column_net: P008
        middle:
          key.stagger: 5
          key.column_net: P002
          key.mirror.column_net: P017
          rows.r5.column_net: P029
          rows.r5.mirror.column_net: P008
        index:
          key.stagger: -6
          rows.r5.skip: true
          key.column_net: P115
          key.mirror.column_net: P020
        inner:
          key.stagger: -2
          rows.r5.skip: true
          key.column_net: P113
          key.mirror.column_net: P022
      rows:
        r5:
          row_net: P106
        r4:
          row_net: P104
        r3:
          row_net: P009
        r2:
          row_net: P010
        r1:
          row_net: P111
    thumbfan:
      key:
        padding: ky
        spread: kx
      anchor:
        ref: matrix_inner_r4
        shift: [-7, -19]
      columns:
        near:
          key.column_net: P002
          key.mirror.column_net: P017
        home:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-11.75, -9]
          key.column_net: P115
          key.mirror.column_net: P020
        far:
          key.spread: 21.25
          key.splay: -28
          key.origin: [-9.5, -9]
          key.column_net: P113
          key.mirror.column_net: P022
      rows:
        thumb:
          row_net: P106
  rotate: -20
  mirror:
    ref: matrix_pinky_r5
    distance: 233.7529778
outlines:
  # Will be used for the mock PCB and the top case
  switchesOutline:
    - what: rectangle
      where: true
      bound: false
      size: [sx,sy]
  # Will be used for the PCB
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  batteryOutline:
    - what: rectangle
      size: [36,52]
      where:
        ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
        shift: [0,-38.5]
        rotate: 90
  board:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        - ref: matrix_pinky_r1
          shift: [-halfX,halfY]
        - ref: matrix_ring_r1
          shift: [-halfX,halfY]
        - ref: matrix_middle_r1
          shift: [-halfX,halfY]
        - ref: matrix_middle_r1
          shift: [halfX,halfY]
        - ref: matrix_inner_r1
          shift: [halfX,halfY]
        - ref: mirror_matrix_inner_r1
          shift: [halfX,halfY]
        - ref: mirror_matrix_middle_r1
          shift: [halfX,halfY]
        - ref: mirror_matrix_middle_r1
          shift: [-halfX,halfY]
        - ref: mirror_matrix_ring_r1
          shift: [-halfX,halfY]
        - ref: mirror_matrix_pinky_r1
          shift: [-halfX,halfY]
        - ref: mirror_matrix_pinky_r4
          shift: [-halfX,-halfY]
        - ref: mirror_matrix_pinky_r4
          shift: [halfX,-halfY]
        - ref: mirror_matrix_middle_r5
          shift: [0,-0.6py]
        - ref: mirror_thumbfan_near_thumb
          shift: [-halfX,-halfY]
        - ref: mirror_thumbfan_near_thumb
          shift: [halfX,-halfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [-halfX,-halfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [halfX,-halfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [halfX,halfY]
        - ref: thumbfan_far_thumb
          shift: [halfX,halfY]
        - ref: thumbfan_far_thumb
          shift: [halfX,-halfY]
        - ref: thumbfan_far_thumb
          shift: [-halfX,-halfY]
        - ref: thumbfan_near_thumb
          shift: [halfX,-halfY]
        - ref: thumbfan_near_thumb
          shift: [-halfX,-halfY]
        - ref: matrix_middle_r5
          shift: [0,-0.6py]
        - ref: matrix_pinky_r4
          shift: [halfX,-halfY]
        - ref: matrix_pinky_r4
          shift: [-halfX,-halfY]
  comboMockPCB:
      - name: board
      - operation: subtract
        name: batteryOutline
      - operation: subtract
        name: switchesOutline
  cutboard:
    - name: board
    - operation: subtract
      name: batteryOutline
  # Cutout for the Nice View Display
  displayCutout:
    - what: rectangle
      size: [14.5,36.5]
      where:
        ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
        shift: [0,4]
  # Cutout for the Rotary Encoder (same size as a switch)
  rotaryEncoderCutout:
    - what: rectangle
      size: [sx,sy]
      where:
        ref.aggregate.parts: [thumbfan_home_thumb, mirror_thumbfan_home_thumb]
        shift: [0, -4]
  # Will be used for the top and bottom cases
  xlBoard:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        - ref: matrix_pinky_r1
          shift: [-dHalfX,dHalfY]
        - ref: matrix_ring_r1
          shift: [-dHalfX,dHalfY]
        - ref: matrix_middle_r1
          shift: [-dHalfX,dHalfY]
        - ref: matrix_middle_r1
          shift: [dHalfX,dHalfY]
        - ref: matrix_inner_r1
          shift: [dHalfX,dHalfY]
        - ref: mirror_matrix_inner_r1
          shift: [dHalfX,dHalfY]
        - ref: mirror_matrix_middle_r1
          shift: [dHalfX,dHalfY]
        - ref: mirror_matrix_middle_r1
          shift: [-dHalfX,dHalfY]
        - ref: mirror_matrix_ring_r1
          shift: [-dHalfX,dHalfY]
        - ref: mirror_matrix_pinky_r1
          shift: [-dHalfX,dHalfY]
        - ref: mirror_matrix_pinky_r4
          shift: [-dHalfX,-dHalfY]
        - ref: mirror_matrix_pinky_r4
          shift: [dHalfX,-dHalfY]
        - ref: mirror_matrix_middle_r5
          shift: [0,-0.6dpy]
        - ref: mirror_thumbfan_near_thumb
          shift: [-dHalfX,-dHalfY]
        - ref: mirror_thumbfan_near_thumb
          shift: [dHalfX,-dHalfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [-dHalfX,-dHalfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [dHalfX,-dHalfY]
        - ref: mirror_thumbfan_far_thumb
          shift: [dHalfX,dHalfY]
        - ref: thumbfan_far_thumb
          shift: [dHalfX,dHalfY]
        - ref: thumbfan_far_thumb
          shift: [dHalfX,-dHalfY]
        - ref: thumbfan_far_thumb
          shift: [-dHalfX,-dHalfY]
        - ref: thumbfan_near_thumb
          shift: [dHalfX,-dHalfY]
        - ref: thumbfan_near_thumb
          shift: [-dHalfX,-dHalfY]
        - ref: matrix_middle_r5
          shift: [0,-0.6dpy]
        - ref: matrix_pinky_r4
          shift: [dHalfX,-dHalfY]
        - ref: matrix_pinky_r4
          shift: [-dHalfX,-dHalfY]
  mounting:
    - what: circle
      radius: screwSize
      where:
        ref: matrix_pinky_r1
        shift: [0.55px, 0.6py]
    - what: circle
      radius: screwSize
      where:
        ref: matrix_ring_r4
        shift: [0, -0.75py]
    - what: circle
      radius: screwSize
      where:
        ref: matrix_index_r4
        shift: [-0.2px, -py]
    - what: circle
      radius: screwSize
      where:
        ref.aggregate.parts: [thumbfan_far_thumb, mirror_thumbfan_far_thumb]
        shift: [0, 0]
    - what: circle
      radius: screwSize
      where:
        ref: mirror_matrix_pinky_r1
        shift: [0.55px, 0.6py]
    - what: circle
      radius: screwSize
      where:
        ref: mirror_matrix_ring_r4
        shift: [0, -0.75py]
    - what: circle
      radius: screwSize
      where:
        ref: mirror_matrix_index_r4
        shift: [-0.2px, -py]
  standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: matrix_pinky_r1
        shift: [0.55px, 0.6py]
    - what: circle
      radius: standoffSize
      where:
        ref: matrix_ring_r4
        shift: [0, -0.75py]
    - what: circle
      radius: standoffSize
      where:
        ref: matrix_index_r4
        shift: [-0.2px, -py]
    - what: circle
      radius: standoffSize
      where:
        ref.aggregate.parts: [thumbfan_far_thumb, mirror_thumbfan_far_thumb]
        shift: [0, 0]
    - what: circle
      radius: standoffSize
      where:
        ref: mirror_matrix_pinky_r1
        shift: [0.55px, 0.6py]
    - what: circle
      radius: standoffSize
      where:
        ref: mirror_matrix_ring_r4
        shift: [0, -0.75py]
    - what: circle
      radius: standoffSize
      where:
        ref: mirror_matrix_index_r4
        shift: [-0.2px, -py]
pcbs:
  wingboard:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
      main:
        outline: cutboard
    footprints:
      choc_keys:
        what: switch_choc_v1_v2
        where: true
        params:
          include_keycap: true
          include_corner_marks: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123
        where: true
        params:
          side: B
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu:
        what: mcu_supermini_nrf52840
        params:
          reverse_mount: true
          include_extra_pins: true
          show_silk_labels_on_both_sides: true
          P1_label: "006"
          P0_label: "008"
          P2_label: "017"
          P3_label: "020"
          P4_label: "022"
          P5_label: "024"
          P6_label: "100"
          P7_label: "011"
          P8_label: "104"
          P9_label: "106"
          P21_label: "031"
          P20_label: "029"
          P19_label: "002"
          P18_label: "115"
          P15_label: "113"
          P14_label: "111"
          P16_label: "010"
          P10_label: "009"
          P101_label: "101"
          P102_label: "102"
          P107_label: "107"
          RAW: "RAW"
          GND: "GND"
          RST: "RST"
          VCC: "VCC"
          P21: "P031"
          P20: "P029"
          P19: "P002"
          P18: "P115"
          P15: "P113"
          P14: "P111"
          P16: "P010"
          P10: "P009"
          P1: "P006"
          P0: "P008"
          P2: "P017"
          P3: "P020"
          P4: "P022"
          P5: "P024"
          P6: "P100"
          P7: "P011"
          P8: "P104"
          P9: "P106"
          P101: "P101"
          P102: "P102"
          P107: "P107"
        where:
          ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
          shift: [0,5]
          rotate: 0
      mcu_text:
        what: utility_text
        where: 
          ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
          shift: [0,5]
          rotate: 90
        params:
          side: "B"
          text: "Supermini NRF52840\\ngoes here"
          mirrored: true
      display:
        what: display_nice_view
        params:
          MOSI: P107
          SCK: P102
          VCC: VCC
          GND: GND
          CS: P101
        where:
          ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
          shift: [0,4]
          rotate: 0
      display_text:
        what: utility_text
        where: 
          ref.aggregate.parts: [matrix_inner_r2, mirror_matrix_inner_r2]
          shift: [0,4]
          rotate: -90
        params:
          side: F
          text: "Nice!View\\ngoes here"
      power_switch:
        what: slide_switch_smd
        params:
            side: B
            from: BAT_P
            to: RAW
        where:
          ref: matrix_index_r1
          shift: [-3.434,13.734]
          rotate: -12.5
      reset:
        what: reset_switch_smd
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_index_r1
          shift: [-3.434,13.684]
          rotate: -12.5
      battery_connector:
        what: battery_connector_jst_ph_2
        params:
          side: B
          BAT_P: BAT_P
          BAT_N: GND
        where:
          ref: mirror_matrix_inner_r2
          shift: [14, 0]
          rotate: 20

      rotary_encoder:
        what: rotary_encoder_ec11_ec12
        params:
          include_plate_hole_marking: true
          A: P024
          B: GND
          C: P100
          S1: P011
          S2: GND
        where:
          ref.aggregate.parts: [thumbfan_home_thumb, mirror_thumbfan_home_thumb]
          shift: [0, -4]
          rotate: 90
      # Mounting holes
      hole_top_left:
        what: mounting_hole_plated
        where:
          ref: matrix_pinky_r1
          shift: [0.55px, 0.6py]
      hole_bottom_left_under_ring:
        what: mounting_hole_plated
        where:
          ref: matrix_ring_r4
          shift: [0, -0.75py]
      hole_bottom_left_under_index:
        what: mounting_hole_plated
        where:
          ref: matrix_index_r4
          shift: [-0.2px, -py]
      hole_center:
        what: mounting_hole_plated
        where:
          ref.aggregate.parts: [thumbfan_far_thumb, mirror_thumbfan_far_thumb]
          shift: [0, 0]
      hole_top_right:
        what: mounting_hole_plated
        where:
          ref: mirror_matrix_pinky_r1
          shift: [0.55px, 0.6py]
      hole_bottom_right_under_ring:
        what: mounting_hole_plated
        where:
          ref: mirror_matrix_ring_r4
          shift: [0, -0.75py]
      hole_bottom_right_under_index:
        what: mounting_hole_plated
        where:
          ref: mirror_matrix_index_r4
          shift: [-0.2px, -py]
      # Filled Zone (GND fill)
      gnd_fill:
        what: utility_filled_zone
        params:
          side: "F&B"
          net: "GND"
          pad_clearance: 0.3
          remove_islands: "never"
      board_name_text:
        what: utility_text
        where: 
          ref.aggregate.parts: [thumbfan_home_thumb, mirror_thumbfan_home_thumb]
          shift: [0, -13]
        params:
          side: "F"
          reversible: true
          text: "WINGBOARD"
          face: "Futura"
          height: 3.5
          width: 3.5
      board_front_text:
        what: utility_text
        where: 
          ref.aggregate.parts: [thumbfan_far_thumb, mirror_thumbfan_far_thumb]
          shift: [0, 4]
        params:
          side: "F"
          text: "Front"
          height: 2
          width: 2
      board_back_text:
        what: utility_text
        where: 
          ref.aggregate.parts: [thumbfan_far_thumb, mirror_thumbfan_far_thumb]
          shift: [0, 4]
        params:
          side: "B"
          text: "Back"
          height: 2
          width: 2
          mirrored: true
cases:
  _bottom:
    - name: board
      extrude: 1
  _xlBottom:
    - name: xlBoard
      extrude: 1
  _outerWall:
    - name: xlBoard
      extrude: 4
  _innerWall:
    - name: board
      extrude: 4
  _wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  caseBottom:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: _xlBottom
      operation: add
    - what: case
      name: _wall
      operation: add
  mockPCB:
    - name: comboMockPCB
      extrude: 1.6